name: Build and Release Extension Charts via PR creation

on:
  workflow_dispatch:
  release:
    types: [released]

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  create-pr-build-extension-charts:
    uses: rancher/dashboard/.github/workflows/create-pr-build-extension-charts.yml@master
    permissions:
      actions: write
      contents: write
      deployments: write
      pages: write
      pull-requests: write
    with:
      target_branch: main
      tagged_release: ${{ github.ref_name }}
